"""Init

Revision ID: 59b0f66059fd
Revises: 
Create Date: 2023-02-18 02:30:05.760187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b0f66059fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('crated_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('ix_contacts_birthday', table_name='contacts')
    op.drop_index('ix_contacts_description', table_name='contacts')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.drop_index('ix_contacts_surname', table_name='contacts')
    op.create_unique_constraint(None, 'contacts', ['phone'])
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.create_index('ix_contacts_surname', 'contacts', ['surname'], unique=False)
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_index('ix_contacts_name', 'contacts', ['name'], unique=False)
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_description', 'contacts', ['description'], unique=False)
    op.create_index('ix_contacts_birthday', 'contacts', ['birthday'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
